# Generated by Django 6.0.3 on 2026-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserved_at", models.DateTimeField(verbose_name="Дата бронирования")),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "customer_contact",
                    models.CharField(
                        max_length=100, verbose_name="Контактная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["reserved_at"],
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=20,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание", verbose_name="Описание"
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание истории",
                        null=True,
                        verbose_name="История ресторана",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание миссии и ценностей",
                        null=True,
                        verbose_name="Миссия и ценности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(unique=True, verbose_name="Номер стола"),
                ),
                ("capacity", models.IntegerField(verbose_name="Вместимость столика")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступность столика"
                    ),
                ),
            ],
        ),
    ]
